#pragma once

#include "nanoxgen/types.h"
#include "nanoxgen/xgen_classic.h"
#include "nanoxgen/xgen_classic_alembic.h"

#include <cstddef>
#include <cstdint>
#include <filesystem>
#include <span>
#include <string>
#include <string_view>
#include <vector>

namespace nanoxgen {

struct ClassicRootGenerationLimits {
    std::uint64_t max_candidates{100000000u};
    std::uint64_t max_roots{100000000u};
};

struct ClassicRootFaceStats {
    std::uint32_t face_id{};
    std::uint32_t candidate_count{};
    std::uint32_t mask_accepted_count{};
    std::uint32_t root_count{};
};

struct ClassicGuideInfluence {
    std::uint32_t guide_index{};
    float weight{};
};

struct ClassicRootPlan {
    std::vector<RootSample> roots;
    // Patch name is part of the motion identity because face IDs are local to
    // each patch and can repeat inside one description.
    std::vector<std::string> patch_names;
    // Reference-pose global position used by Classic's $Prefg expression
    // variable. This remains separate from the current renderer root.
    std::vector<Vec3> reference_positions;
    // Current-pose XGen cU frame direction used by authored FX modules.
    std::vector<Vec3> surface_tangents;
    // XGen resets the renderer primitive ID for every patch face and counts
    // RandomGenerator candidates from one. Rejected mask samples therefore
    // leave observable gaps in later $id expressions.
    std::vector<std::uint32_t> primitive_ids;
    // SeExpr hash state after exact double (u,v,faceSeed) ingestion. Runtime
    // rand() appends its call-site/explicit seed using uint arithmetic only.
    std::vector<std::uint32_t> random_prefixes;
    // CSR guide association generated by XGen's directional support test.
    // Empty means that the imported guides did not carry Classic support
    // metadata; otherwise this contains roots.size() + 1 entries.
    std::vector<std::uint32_t> influence_offsets;
    std::vector<ClassicGuideInfluence> influences;
    std::vector<std::filesystem::path> ptex_maps;
    std::vector<ClassicRootFaceStats> face_stats;
    std::uint64_t candidate_count{};
    std::uint64_t mask_rejected_count{};
    std::uint64_t patch_culled_count{};
    std::uint64_t guide_rejected_count{};
};

// The deformation-varying portion of a Classic root plan. All association,
// PTEX, random, and primitive identity data remains in the reference plan and
// can be shared by every motion sample.
struct ClassicDeformedRootPlan {
    std::vector<RootSample> roots;
    std::vector<Vec3> surface_tangents;
};

// Sample-invariant root-to-coarse-face lookup for motion deformation. Building
// it once validates root identity uniqueness and turns every later sample
// rebind into a linear pass over roots.
struct ClassicRootDeformationTopology {
    std::vector<std::uint32_t> surface_face_indices;
};

struct ClassicExplicitRoot {
    std::uint32_t face_id{};
    Vec2 uv{};
    Vec3 position{};
    std::uint32_t primitive_id{};
};

// Raw XGen guide-association weight before normalization. Exposed for
// calibration/differential tests; production callers normally use the root
// planner, which rejects samples whose complete guide-weight sum is empty.
[[nodiscard]] float evaluate_xgen_classic_guide_weight(
    const GuideInput &guide, Vec3 reference_position,
    Vec3 reference_normal) noexcept;

[[nodiscard]] float evaluate_xgen_classic_random_mask(
    const ClassicDescription &description,
    const std::filesystem::path &description_directory,
    std::string_view patch_name, std::uint32_t face_id,
    float u, float v);

// Evaluate RandomGenerator density and mask against imported coarse faces.
// description_directory is the concrete expansion of ${DESC}; PTEX is decoded
// before GPU execution and roots retain stable (faceId,u,v) identities.
[[nodiscard]] ClassicRootPlan build_xgen_classic_random_root_plan(
    const ClassicDescription &description,
    const ClassicAlembicAssetInput &surface,
    const std::filesystem::path &description_directory,
    const ClassicRootGenerationLimits &limits = {});

// Select the root planner authored by the description's Active generator.
// GuideGenerator emits one strand per authored guide; RandomGenerator uses
// the density/mask path above.
[[nodiscard]] ClassicRootPlan build_xgen_classic_root_plan(
    const ClassicDescription &description,
    const ClassicAlembicAssetInput &surface,
    const std::filesystem::path &description_directory,
    const ClassicRootGenerationLimits &limits = {});

// Associate caller-provided patch locations with the description's authored
// guides. XPD clump points retain face/u/v identity and face-local primitive
// IDs; their cached authoring-position xyz is validated, while the evaluated
// root is sampled from the current render patch.
[[nodiscard]] ClassicRootPlan build_xgen_classic_explicit_root_plan(
    const ClassicDescription &description,
    const ClassicAlembicAssetInput &surface,
    const std::filesystem::path &description_directory,
    std::string_view patch_name,
    std::span<const ClassicExplicitRoot> samples);

// Re-evaluate an existing root topology on another Alembic sample. Identity
// and guide association are never regenerated, so RandomGenerator mask
// thresholds and PTEX/XPD bindings stay bit-stable across the shutter.
[[nodiscard]] ClassicDeformedRootPlan deform_xgen_classic_root_plan(
    const ClassicRootPlan &reference,
    const ClassicAlembicAssetInput &surface);

[[nodiscard]] ClassicRootDeformationTopology
prepare_xgen_classic_root_deformation(
    const ClassicRootPlan &reference,
    const ClassicAlembicAssetInput &reference_surface);

[[nodiscard]] ClassicDeformedRootPlan deform_xgen_classic_root_plan(
    const ClassicRootPlan &reference,
    const ClassicRootDeformationTopology &topology,
    const ClassicAlembicAssetInput &surface);

// Rebuild each authored guide using XGen's uniform SgCurve convention, then
// blend guide offsets with the exact associations retained by the root plan.
// The final renderer payload remains float4(position, radius); double is used
// only for the host-side SgCurve-compatible intermediate arithmetic.
[[nodiscard]] PackedGeneratedCurves generate_xgen_classic_base_curves_cpu(
    const AssetBuildInput &asset,
    const ClassicRootPlan &roots,
    std::uint32_t cvs_per_strand,
    float diameter = 0.0f,
    float radius_scale = 1.0f,
    bool root_relative = false);

// Translate a root-relative fixed-CV curve set to renderer world positions.
// Keeping Classic generation/FX local until this final addition avoids losing
// segment precision when world coordinates are much larger than strand
// offsets. The function is deliberately explicit to prevent double-translation.
void make_xgen_classic_curves_world_space(PackedGeneratedCurves &curves);

// Flatten XGen's uniformly rebuilt guide CVs as guide-major float3 data for
// renderer/GPU upload. Rebuilding is a one-time host operation; device kernels
// consume only float data and never require FP64 support.
[[nodiscard]] std::vector<Vec3> rebuild_xgen_classic_guides_for_device(
    const AssetBuildInput &asset,
    std::uint32_t cvs_per_guide);

} // namespace nanoxgen
